import NavBar from "./components/NavBar";
import Hero from "./components/Hero";
import Main from "../app/components/Main";

export const metadata = {
  title: "decoration",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
    <Hero />
    <Main />
    </>
  );
}
