import NavBar from "./components/NavBar";
import Hero from "./components/Hero";

export const metadata = {
  title: "decoration",
  description: "Generated by create next app",
};

export default function Home() {
  return (
    <>
    <NavBar />
    <Hero />
    </>
  );
}
